### ISSUE TITLE
Branch on fork of lakion/mink-debug-extension does not exist anymore

### ISSUE THREAD

**Issue by DieterHolvoet** [nedac-sorbo/SyliusMinimumOrderValuePlugin#1]
When running `composer install` in the cloned repo, I get this error:
```
The requested package lakion/mink-debug-extension dev-feature/decouple-listener-from-driver-implementations as 1.2.3 exists as lakion/mink-debug-extension[dev-master, v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.2.3] but these are rejected by your constraint.
```
The referenced feature branch was deleted, but I can't figure out whether or not the feature was merged.

**Comment by 4c0n** [comment]
@DieterHolvoet It was merged, but no new release/tag was created. So I guess the only valid version constraint we can use now is: "dev-master#9c3ecc09b83967a392a7c13c8f8c8502a3f50d4f" which is also not ideal. It took me a long time and lots of effort just to get that little bit merged:

https://github.com/FriendsOfBehat/MinkDebugExtension/pull/33
https://github.com/FriendsOfBehat/MinkDebugExtension/pull/34

As you can read in the comments, the team does not seem to have any time to spend on that package and they can't tell when they will, so if something else/better is available it's probably a good idea to switch to that package (basically didn't change anything after 2016).

**Comment by DieterHolvoet** [comment]
Personally, I don't have much experience with testing, so I can't really propose an alternative. For now, I'll make a PR to switch to the `dev-master#9c3ecc09b83967a392a7c13c8f8c8502a3f50d4f` version.

**Comment by 4c0n** [comment]
@DieterHolvoet Awesome, thanks!
