### ISSUE TITLE
Error when creating the order from the admin section

### ISSUE THREAD

**Issue by SylvanoTombo** [nedac-sorbo/SyliusMinimumOrderValuePlugin#13]
When i activated the minimum order and create an order from the admin section, it show up an error

![image](https://user-images.githubusercontent.com/40351002/116213291-55944480-a74e-11eb-8f40-5ca4bc009cb5.png)

**Comment by SylvanoTombo** [comment]
I think, it's due to the AdminOrderCreationPlugin which i used. v0.2.1.

**Comment by SylvanoTombo** [comment]
@nedac-sorbo , Maybe! we should add an option to deactivate the guard if in admin section?

**Comment by 4c0n** [comment]
@SylvanoTombo I think that is supposed happen and the guard should not be "disabled", guards not conditional.
If anything I think you would want to handle this case better in the AdminOrderCreation plugin or in the project itself, as obviously things could go wrong when creating an order.
